(lang dune 3.4)

(name app)

(generate_opam_files true)

(source
 (github y2k/github-pages-builder))

(authors "y2k")

(license LICENSE)

(package
 (name app)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml dune)
 (tags
  (topics "to describe" your project)))
